---
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse  = TRUE,
  comment   = "#>",
  fig.path  = "man/figures/README-",
  out.width = "100%"
)

Sys.setenv(MINION_PATH = "/home/matthew/bin/minion-1.8")
```

# rminion

A simple wrapper around the
[Minion](https://github.com/minion/minion)
constraint solver.

## Installation

### Minion

To install Minion, download the Minion repository. The
Minion executable is found in the `bin/` folder.

More details here: https://github.com/minion/minion

### R Package

```{r eval = FALSE}
remotes::install_github("MHenderson/rminion")
```

## Example: Donald, Gerald, Robert

```{r eval = TRUE}
dgr <- "
MINION 3
**VARIABLES**
DISCRETE a{0..9}
DISCRETE b{0..9}
DISCRETE d{0..9}
DISCRETE e{0..9}
DISCRETE g{0..9}
DISCRETE l{0..9}
DISCRETE n{0..9}
DISCRETE o{0..9}
DISCRETE r{0..9}
DISCRETE t{0..9}
**SEARCH**
VARORDER [a,b,d,e,g,l,n,o,r,t]
VALORDER [a,a,a,a,a,a,a,a,a,a]
SYMORDER [a,b,d,e,g,l,n,o,r,t]
PRINT[[a],[b],[d],[e],[g],[l],[n],[o],[r],[t]]
**CONSTRAINTS**
weightedsumleq([100000,10000,1000,100,10,1,100000,10000,1000,100,10,1,-100000,-10000,-1000,-100,-10,-1], [d,o,n,a,l,d,g,e,r,a,l,d,r,o,b,e,r,t], 0)
weightedsumgeq([100000,10000,1000,100,10,1,100000,10000,1000,100,10,1,-100000,-10000,-1000,-100,-10,-1], [d,o,n,a,l,d,g,e,r,a,l,d,r,o,b,e,r,t], 0)
gacalldiff([a,b,d,e,g,l,n,o,r,t])
**EOF**"
```

```{r}
library(readr)

dgr_file <- tempfile()
write_file(dgr, dgr_file)
```


```{r}
library(rminion)

minion(dgr_file)
```
